In [1]:
import pandas as pd

In [44]:
df=pd.read_csv('julio.csv')
df.head()

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,"Wed, May 1, 2024",7:30p,Miami Heat,84.0,Boston Celtics,118.0,Box Score,NaN,"19,156",TD Garden,NaN
1,"Wed, May 1, 2024",10:00p,Dallas Mavericks,123.0,Los Angeles Clippers,93.0,Box Score,NaN,"19,37",Crypto.com Arena,NaN
2,"Thu, May 2, 2024",6:30p,Milwaukee Bucks,98.0,Indiana Pacers,120.0,Box Score,NaN,"17,274",Gainbridge Fieldhouse,NaN
3,"Thu, May 2, 2024",9:00p,New York Knicks,118.0,Philadelphia 76ers,115.0,Box Score,NaN,"21,093",Wells Fargo Center,NaN
4,"Fri, May 3, 2024",7:00p,Cleveland Cavaliers,96.0,Orlando Magic,103.0,Box Score,NaN,"19,193",Kia Center,NaN

In [45]:
calendario=pd.concat([calendario,df])

In [46]:
calendario

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Arena,Notes
0,"Tue, Oct 24, 2023",7:30p,Los Angeles Lakers,107.0,Denver Nuggets,119.0,Box Score,NaN,"19,842",Ball Arena,NaN
1,"Tue, Oct 24, 2023",10:00p,Phoenix Suns,108.0,Golden State Warriors,104.0,Box Score,NaN,"18,064",Chase Center,NaN
2,"Wed, Oct 25, 2023",7:00p,Houston Rockets,86.0,Orlando Magic,116.0,Box Score,NaN,"18,846",Kia Center,NaN
3,"Wed, Oct 25, 2023",7:00p,Boston Celtics,108.0,New York Knicks,104.0,Box Score,NaN,"19,812",Madison Square Garden (IV),NaN
4,"Wed, Oct 25, 2023",7:00p,Washington Wizards,120.0,Indiana Pacers,143.0,Box Score,NaN,"16,004",Gainbridge Fieldhouse,NaN
...,...,...,...,...,...,...,...,...,...,...,...
36,"Sat, May 25, 2024",8:30p,Boston Celtics,114.0,Indiana Pacers,111.0,Box Score,NaN,"17,274",Gainbridge Fieldhouse,NaN
37,"Sun, May 26, 2024",8:00p,Minnesota Timberwolves,107.0,Dallas Mavericks,116.0,Box Score,NaN,"20,511",American Airlines Center,NaN
38,"Mon, May 27, 2024",8:00p,Boston Celtics,105.0,Indiana Pacers,102.0,Box Score,NaN,"17,274",Gainbridge Fieldhouse,NaN
39,"Tue, May 28, 2024",8:30p,Minnesota Timberwolves,105.0,Dallas Mavericks,100.0,Box Score,NaN,"20,477",American Airlines Center,NaN
40,"Thu, May 30, 2024",8:30p,Dallas Mavericks,NaN,Minnesota Timberwolves,NaN,NaN,NaN,NaN,Target Center,NaN

Ahora a limpiarl para hacer el merge

In [51]:
calendario = calendario[['Date','Visitor/Neutral','Home/Neutral']]

In [52]:
calendario

                 Date         Visitor/Neutral            Home/Neutral
0   Tue, Oct 24, 2023      Los Angeles Lakers          Denver Nuggets
1   Tue, Oct 24, 2023            Phoenix Suns   Golden State Warriors
2   Wed, Oct 25, 2023         Houston Rockets           Orlando Magic
3   Wed, Oct 25, 2023          Boston Celtics         New York Knicks
4   Wed, Oct 25, 2023      Washington Wizards          Indiana Pacers
..                ...                     ...                     ...
36  Sat, May 25, 2024          Boston Celtics          Indiana Pacers
37  Sun, May 26, 2024  Minnesota Timberwolves        Dallas Mavericks
38  Mon, May 27, 2024          Boston Celtics          Indiana Pacers
39  Tue, May 28, 2024  Minnesota Timberwolves        Dallas Mavericks
40  Thu, May 30, 2024        Dallas Mavericks  Minnesota Timberwolves

[1314 rows x 3 columns]

In [54]:
calendario['Date']= pd.to_datetime(calendario['Date'])

C:\Users\iauzm\AppData\Local\Temp\ipykernel_29344\2322946407.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  calendario['Date']= pd.to_datetime(calendario['Date'])

In [55]:
calendario.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1314 entries, 0 to 40
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             1314 non-null   datetime64[ns]
 1   Visitor/Neutral  1314 non-null   object
 2   Home/Neutral     1314 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 41.1+ KB

In [56]:
calendario.to_csv('calendario.csv')