In [1]:
import pandas as pd

In [20]:
import requests
import pandas as pd

# Send GET request to the JSON API endpoint
response = requests.get("https://site.web.api.espn.com/apis/fitt/v3/sports/basketball/nba/powerindex?region=us&lang=en&sort=projections.projectedw%3Adesc")

# Check if the request was successful
if response.status_code == 200:
    # Parse JSON response data
    data = response.json()

    # Extract relevant information from the JSON structure
    teams = []
    for team in data['teams']:
        team_info = {
            'team_id': team['team']['id'],
            'team_name': team['team']['name'],
            'abbreviation':team['team']['abbreviation'] 
     
        }
        teams.append(team_info)

    # Create a Pandas DataFrame from the extracted data
    df = pd.DataFrame(teams)

    # Print the DataFrame
    print(df)
else:
    print(f"Error: Unable to access API. Status code: {response.status_code}")

   team_id      team_name abbreviation
0        2        Celtics          BOS
1        7        Nuggets          DEN
2       25        Thunder          OKC
3       16   Timberwolves          MIN
4       12       Clippers          LAC
5        6      Mavericks          DAL
6       18         Knicks           NY
7        3       Pelicans           NO
8       15          Bucks          MIL
9       21           Suns          PHX
10       5      Cavaliers          CLE
11      11         Pacers          IND
12      13         Lakers          LAL
13      19          Magic          ORL
14      20          76ers          PHI
15       9       Warriors           GS
16      14           Heat          MIA
17      23          Kings          SAC
18      10        Rockets          HOU
19       4          Bulls          CHI
20       1          Hawks          ATL
21      17           Nets          BKN
22      26           Jazz         UTAH
23      29      Grizzlies          MEM
24      28        Raptors          TOR
25      24          Spurs           SA
26      22  Trail Blazers          POR
27      30        Hornets          CHA
28      27        Wizards          WSH
29       8        Pistons          DET

In [44]:
info_team=[]
for team in data['teams']:
    info_team.append(team['categories'][0]['totals'])
print(info_team)

[['8.075', '1st', '6.593', '1.482', '8.075', '-', '-', '75', '20'], ['4.684', '5th', '2.487', '2.197', '4.684', '-', '-', '64', '30'], ['5.060', '3rd', '2.404', '2.657', '5.060', '-', '-', '63', '29'], ['4.728', '4th', '1.192', '3.536', '4.728', '-', '-', '64', '32'], ['3.726', '7th', '3.481', '0.245', '3.726', '-', '-', '53', '35'], ['6.116', '2nd', '3.479', '2.637', '6.116', '-', '-', '61', '36'], ['2.800', '11th', '2.409', '0.390', '2.800', '-', '-', '57', '38'], ['1.782', '12th', '0.398', '1.384', '1.782', '-', '-', '49', '37'], ['-3.353', '23rd', '-0.695', '-2.658', '-3.353', '-', '-', '51', '37'], ['1.481', '14th', '1.627', '-0.147', '1.481', '-', '-', '49', '37'], ['3.055', '9th', '0.600', '2.456', '3.055', '-', '-', '53', '41'], ['2.918', '10th', '4.737', '-1.818', '2.918', '-', '-', '55', '43'], ['1.604', '13th', '2.197', '-0.593', '1.604', '-', '-', '48', '39'], ['0.824', '17th', '-2.175', '2.999', '0.824', '-', '-', '50', '39'], ['3.339', '8th', '1.452', '1.887', '3.339', '-', '-', '49', '39'], ['1.327', '15th', '1.580', '-0.253', '1.327', '-', '-', '46', '36'], ['4.609', '6th', '0.104', '4.505', '4.609', '-', '-', '47', '40'], ['0.937', '16th', '0.781', '0.156', '0.937', '-', '-', '46', '36'], ['-0.617', '19th', '-0.713', '0.096', '-0.617', '-', '-', '41', '41'], ['-0.836', '20th', '0.598', '-1.434', '-0.836', '-', '-', '39', '43'], ['-1.485', '21st', '0.922', '-2.407', '-1.485', '-', '-', '36', '46'], ['-4.156', '25th', '-3.599', '-0.558', '-4.156', '-', '-', '32', '50'], ['-3.853', '24th', '0.452', '-4.305', '-3.853', '-', '-', '31', '51'], ['-0.256', '18th', '-3.388', '3.132', '-0.256', '-', '-', '27', '55'], ['-5.504', '26th', '-2.258', '-3.245', '-5.504', '-', '-', '25', '57'], ['-2.411', '22nd', '-2.686', '0.275', '-2.411', '-', '-', '22', '60'], ['-5.867', '27th', '-4.909', '-0.957', '-5.867', '-', '-', '21', '61'], ['-7.752', '28th', '-4.775', '-2.977', '-7.752', '-', '-', '21', '61'], ['-11.703', '30th', '-6.475', '-5.228', '-11.703', '-', '-', '15', '67'], ['-10.147', '29th', '-6.258', '-3.890', '-10.147', '-', '-', '14', '68']]

In [53]:
i=0
bpi_list=[]
bpi_rk_list=[]
off_list=[]
def_list=[]
pbpi_list=[]
wins_list=[]
loses_list=[]
for datos in info_team:
    bpi_list.append(datos[0])
    bpi_rk_list.append(datos[1])
    off_list.append(datos[2])
    def_list.append(datos[3])
    pbpi_list.append(datos[4])
    wins_list.append(datos[7])
    loses_list.append(datos[8])
    i+=1
df.head()

  team_id     team_name abbreviation
0       2       Celtics          BOS
1       7       Nuggets          DEN
2      25       Thunder          OKC
3      16  Timberwolves          MIN
4      12      Clippers          LAC

In [57]:
df['bpi']=pd.DataFrame(bpi_list)
df['bpi_rk']=pd.DataFrame(bpi_rk_list)
df['off']=pd.DataFrame(off_list)
df['def']=pd.DataFrame(def_list)
df['pbpi']=pd.DataFrame(pbpi_list)
df['wins']=pd.DataFrame(wins_list)
df['loses']=pd.DataFrame(loses_list)

In [58]:
df

,team_id,team_name,abbreviation,bpi,bpi_rk,off,def,pbpi,wins,loses
0,2,Celtics,BOS,8.075,1st,6.593,1.482,8.075,75,20
1,7,Nuggets,DEN,4.684,5th,2.487,2.197,4.684,64,30
2,25,Thunder,OKC,5.060,3rd,2.404,2.657,5.060,63,29
3,16,Timberwolves,MIN,4.728,4th,1.192,3.536,4.728,64,32
4,12,Clippers,LAC,3.726,7th,3.481,0.245,3.726,53,35
5,6,Mavericks,DAL,6.116,2nd,3.479,2.637,6.116,61,36
6,18,Knicks,NY,2.800,11th,2.409,0.390,2.800,57,38
7,3,Pelicans,NO,1.782,12th,0.398,1.384,1.782,49,37
8,15,Bucks,MIL,-3.353,23rd,-0.695,-2.658,-3.353,51,37
9,21,Suns,PHX,1.481,14th,1.627,-0.147,1.481,49,37
10,5,Cavaliers,CLE,3.055,9th,0.600,2.456,3.055,53,41
11,11,Pacers,IND,2.918,10th,4.737,-1.818,2.918,55,43
12,13,Lakers,LAL,1.604,13th,2.197,-0.593,1.604,48,39
13,19,Magic,ORL,0.824,17th,-2.175,2.999,0.824,50,39
14,20,76ers,PHI,3.339,8th,1.452,1.887,3.339,49,39
15,9,Warriors,GS,1.327,15th,1.580,-0.253,1.327,46,36
16,14,Heat,MIA,4.609,6th,0.104,4.505,4.609,47,40
17,23,Kings,SAC,0.937,16th,0.781,0.156,0.937,46,36
18,10,Rockets,HOU,-0.617,19th,-0.713,0.096,-0.617,41,41
19,4,Bulls,CHI,-0.836,20th,0.598,-1.434,-0.836,39,43
20,1,Hawks,ATL,-1.485,21st,0.922,-2.407,-1.485,36,46
21,17,Nets,BKN,-4.156,25th,-3.599,-0.558,-4.156,32,50
22,26,Jazz,UTAH,-3.853,24th,0.452,-4.305,-3.853,31,51
23,29,Grizzlies,MEM,-0.256,18th,-3.388,3.132,-0.256,27,55
24,28,Raptors,TOR,-5.504,26th,-2.258,-3.245,-5.504,25,57
25,24,Spurs,SA,-2.411,22nd,-2.686,0.275,-2.411,22,60
26,22,Trail Blazers,POR,-5.867,27th,-4.909,-0.957,-5.867,21,61
27,30,Hornets,CHA,-7.752,28th,-4.775,-2.977,-7.752,21,61
28,27,Wizards,WSH,-11.703,30th,-6.475,-5.228,-11.703,15,67
29,8,Pistons,DET,-10.147,29th,-6.258,-3.890,-10.147,14,68

### GLOSARIO

* BPI:Basketball Power Index that measures team’s true strength on net points scale; expected point margin vs average opponent on neutral court.
* BPI RK:Basketball Power Index Rank vs all NBA teams
* OFF:Offensive component of BPI. Offensive contribution to expected point margin vs average opponent on neutral court.
* DEF:Defensive component of BPI. Defensive contribution to expected point margin vs average opponent on neutral court.
* PBPI:Playoff BPI. Average BPI value throughout the course of the playoffs. Includes past, currently-scheduled, and hypothetical future playoff games
* WINS: victories of the team this season
* LOSES: loses of the team this season

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   team_id       30 non-null     object
 1   team_name     30 non-null     object
 2   abbreviation  30 non-null     object
 3   bpi           30 non-null     object
 4   bpi_rk        30 non-null     object
 5   off           30 non-null     object
 6   def           30 non-null     object
 7   pbpi          30 non-null     object
 8   wins          30 non-null     object
 9   loses         30 non-null     object
dtypes: object(10)
memory usage: 2.5+ KB

### DATA CLEANING

* Son todo tipo object. habrá que cambiarlo
* el bpi_rk no me sirve para nada, lo quito
* el team_id tampoco me sirve, lo quito
* convierto a numerical las columnas que se pueden. 
* Dejo la abreviatura para asociarla a los otros datasets que tengo.

In [64]:
df.drop(columns=['bpi_rk','team_id'],inplace=True)
df[['bpi',  'off', 'def',
       'pbpi', ]]= df[['bpi',  'off', 'def',
       'pbpi', ]].astype(float)
df[['wins','loses']]= df[['wins','loses']].astype(int)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   team_name     30 non-null     object
 1   abbreviation  30 non-null     object
 2   bpi           30 non-null     float64
 3   off           30 non-null     float64
 4   def           30 non-null     float64
 5   pbpi          30 non-null     float64
 6   wins          30 non-null     int32
 7   loses         30 non-null     int32
dtypes: float64(4), int32(2), object(2)
memory usage: 1.8+ KB

#### Creo el csv con los datos limpios

In [66]:
df.to_csv('indicadores.csv')